import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./_layout/page";

export const metadata: Metadata = {
  title: "Bug Bug",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg" sizes="any" />
      </head>
      <body
        className="antialiased"
      >
        <Navigation/>
        {children}
      </body>
    </html>
  );
}
