import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./_layout/page";

import { Inclusive_Sans } from 'next/font/google'

const inclusive = Inclusive_Sans({ weight:'400' })

export const metadata: Metadata = {
  title: "Bug Bug",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./favicon.svg" type="image/svg" sizes="any" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
      </head>
      <body
        className={inclusive.className}
      >
        <Navigation/>
        {children}
      </body>
    </html>
  );
}
